### ISSUE TITLE
Could you please release the latest version with logging control for ffmpeg

### ISSUE THREAD

**Issue by SunDoge** [zhreshold/decord-distro#1]
The ffmpeg logging is really annoying when doing experiments on UCF101. Thx.

**Comment by zhreshold** [comment]
See efa994dd5740e390d559bf48969fad21ed489eb2

**Comment by zhreshold** [comment]
I am having issue with mac os build, but will be fixing that

**Comment by SunDoge** [comment]
`Decord` really helps me with my research. Thank you very much!
